/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:90: ast_inspector:tcltk_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:22: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:86: tcltk_bv_get_tops
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:125: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:132: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:139: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:147: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:149: tcltk_bv_get_unlimited_value
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:213: tcltk_bv_get_value
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:235: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:473: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:476: "bvisual2:bv_print_to_file
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:485: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:487: "bvisual2:bv_write_all_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:618: "bvisual2:tcltk_register_new_user_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:48: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:50: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:61: version:version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:64: prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:67: version:revision
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:69: version:lastchangeddate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:239: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:255: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:279: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:281: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:310: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:347: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:348: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:547: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:845: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:851: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:874: debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:875: show_perfmessages
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:897: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:903: (nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:906: state_space_initialise_with_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:985: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:997: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1001: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1006: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1030: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1033: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1036: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1039: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1069: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1074: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1149: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1158: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1171: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1175: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1186: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1190: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1217: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1238: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1245: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1288: "tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1290: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1333: "tcltk_show_expression_as_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1351: "tcltk_eval_as_table
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1352: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1410: "tcltk_explore_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1413: get_csp_process_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1417: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1426: "tcltk_visualize_csp_process
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1445: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1452: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1501: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1503: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1524: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1542: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1756: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1806: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1807: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1814: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1985: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1993: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1997: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2031: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2048: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2070: tcltk_has_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2083: tcltk_show_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2095: tcltk_get_detailed_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2100: can_generate_dot_from_last_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2127: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2133: "eclipse_interface:ops_user_interrupt_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2146: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2155: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2160: plugins:plugin_has_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2161: plugins:plugins_with_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2179: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2182: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2185: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2198: plugins:plugin_is_available_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2199: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2217: plugins:start_plugin_for_current_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2230: plugins:plugin_has_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2233: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2245: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2262: plugins:stop_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2273: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2276: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2285: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2287: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2295: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2329: "animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2356: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2367: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2379: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2382: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2576: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2592: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2612: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2614: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2616: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2617: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2791: "animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2932: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3212: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3214: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3642: system:environ
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5725: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5733: tcltk_goto_an_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5754: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5765: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5773: parsercall:check_java_version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5775: parsercall:get_version_from_parser
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5793: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5806: perform_verbose_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5819: get_module_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5822: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5880: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5883: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5937: plugins:plugin_file_extensions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5964: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5970: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5984: "unset_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6001: plugins:is_plugin_file_extension
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6009: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6038: tcltk_load_packaged_eventb_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6042: bmachine:b_show_machine_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6099: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6105: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6108: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6112: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6116: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6119: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6122: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6125: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6133: tcltk_get_command_line_file_to_open
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6140: tcltk_get_command_line_tcltk_commands
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6159: tcltk_open_xtl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6301: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6306: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6308: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6329: tcltk_open_z_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6351: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6379: eclipse_interface:load_prob_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6380: tcltk_open_b_file_for_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6384: set_animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6442: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6443: "tools:platform_is_64_bit
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6488: plugins:load_plugin_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6514: tcltk_open_promela_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6543: tcltk_open_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6558: "set_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6570: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6636: tcltk_add_csp_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6695: tcltk_open_b_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6822: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6824: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6858: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6884: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6904: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6905: plugins:tcl_plugin_syntax_colouring
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6926: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6954: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6958: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6963: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6966: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6972: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6977: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6981: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6989: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7002: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7006: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7012: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7018: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7026: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7030: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7039: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7045: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7053: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7079: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7082: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7086: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7091: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7096: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7100: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7104: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7108: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7118: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7121: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7125: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7129: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7133: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7145: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7148: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7153: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7158: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7162: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7167: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7172: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7177: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7187: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7190: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7195: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7199: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7204: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7208: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7212: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7221: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7224: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7229: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7235: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7241: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7246: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7257: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7279: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7308: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7345: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7346: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7349: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7352: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7355: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7359: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7362: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7365: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7368: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7404: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7439: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7441: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7453: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7463: "b_show_history:write_values_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7491: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7589: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7600: tcltk_prepare_for_reload
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7615: plugins:is_registered_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7663: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7674: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7679: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7754: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7757: tcltk_current_state_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7766: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7793: tcltk_execute_until
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7818: "tcltk_execute_model
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7846: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7903: cli_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7904: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7906: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7909: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7915: tcltk_load_commandline_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7918: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7919: file_systems:file_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7920: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7922: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8044: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8057: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8059: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8081: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8084: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8165: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8166: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8172: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8174: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8179: preference_default_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8181: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8193: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8193: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8194: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8195: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8202: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8211: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8219: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8327: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8331: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8335: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8372: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8373: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8377: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8439: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8440: tcltk_unique_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8445: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8519: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8546: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8546: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8553: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8617: tcltk_add_user_executed_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8629: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8630: interruptable_call
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8641: query does not fail 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8642: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8643: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8645: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8699: interruptable_call
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8736: tcltk_analyse_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8738: "register_conjunct_register_error_span
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8770: "reset_conjunct_error_hook
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8783: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8809: tcltk_show_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8820: preferences:get_non_default_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8981: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8985: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8994: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9002: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9003: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9011: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9054: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9056: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9061: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9077: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9082: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9110: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9113: parsercall:ensure_console_parser_launched
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9256: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9328: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9335: last_expression_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9343: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9365: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9374: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9383: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9403: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9489: tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9495: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9498: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9517: "interruptable_tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9523: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9532: "b_simplifier: tcltk_simplify_b_predicate_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9535: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9554: get_error_positions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9561: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9587: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9723: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9724: popup
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9732: bmachine:tcltk_get_specialized_invariants_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9738: b_read_write_info:tcltk_get_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9744: b_read_write_info:tcltk_get_parameter_free_guards_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9753: bmachine:tcltk_get_specialized_invariant_for_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9761: tcltk_cbc_symbolic_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9771: before_after_predicates:tcltk_before_after_predicate_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9780: value_persistance:tcltk_load_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9790: runtime_profiler:tcltk_get_profile_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9807: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9812: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9872: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9895: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9896: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9904: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9906: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9907: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9913: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9917: bmachine:b_write_eventb_machine_to_classicalb_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10110: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10141: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10150: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10205: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10206: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10281: tcltk_dbf_modes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10290: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10302: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10311: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10318: operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10324: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10361: tcltk_state_space_only_has_root_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10369: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10394: tcltk_set_dbf_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10409: "prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10411: "nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10412: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10435: "statistics
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10437: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10442: tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10447: state_space:operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10450: model_checker:proof_info_model_checking_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10453: time_out_for_invariant
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10457: tcltk_hash_model_checking_imprecise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10465: state_error_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10515: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10611: tcltk_ltsmin_init
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10621: cbc_get_uncovered_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10625: sap:tcl_get_stored_test_cases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10647: tcl_execute_stored_test_case
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10667: sap:tcl_generate_testcases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10788: sap:tcl_create_local_testsuite
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10871: set_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10874: specfile:get_internal_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10882: unset_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10888: predicate_debugger:tcltk_get_unsat_core_with_types
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10895: bmachine:b_show_eventb_as_classicalb
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10974: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10985: b_set_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10995: get_error_span_linecol_for_main_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10999: get_error_span_linecol
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11003: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11014: "tools_commands:show_errors_with_bb_results
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11021: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11029: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11034: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11035: backup_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11042: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11054: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11064: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11089: tcltk_goto_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11097: tcltk_goto_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11106: tcltk_goto_a_non_resetable_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11115: tcltk_goto_a_non_deterministic_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11122: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11125: tcltk_goto_node_with_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11134: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11143: tcltk_goto_a_branching_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11158: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11164: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11213: tcltk_goto_event_list_property_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11217: sap:get_selected_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11218: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11233: tcltk_goto_state_enabling_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11236: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11261: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11263: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11290: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11330: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11336: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11342: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11374: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11375: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11385: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11390: tcltk_constraint_find_valid_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11396: tcltk_constraint_find_valid_state_with_goal_pred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11411: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11427: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11435: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11440: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11445: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11452: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11453: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11467: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11485: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11486: tcltk_constraint_find_deadlock_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11499: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11504: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11505: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11518: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11523: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11524: tcltk_constraint_find_static_assertion_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11544: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11548: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11548: unfixed_deferred_set
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11643: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11685: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11692: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11729: {tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11738: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11765: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11765: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11766: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11767: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11796: tcltk_current_node_has_no_real_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11798: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11798: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11798: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11800: tcltk_current_node_has_partial_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11801: preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11822: b_interpreter:tcltk_unsatisfiable_components_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11838: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11838: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11843: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11849: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11860: b_interpreter:tcltk_quick_describe_unsat_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11871: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11876: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11878: {get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11879: {get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11880: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11891: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11903: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11940: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11964: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11980: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11984: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12016: tcltk_can_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12023: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12036: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12048: {tcltk_get_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12064: and insert them
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12070: {tcltk_get_state_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12084: and insert them to the listbox
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12090: {tcltk_get_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12119: csp_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12131: tcltk_get_line_col
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12142: tcltk_is_sync_event
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12167: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12181: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12186: tcltk_perform_nr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12198: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12208: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12213: tcltk_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12239: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12394: get_cbc_data_base_id_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12394: get_cbc_data_base_text_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12602: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12606: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12610: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12613: assert_real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12619: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12621: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12637: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12643: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12691: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12713: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12751: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12792: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12844: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12906: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13085: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13158: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13169: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13279: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13295: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13297: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13328: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13560: "get_ltl_formulas_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13577: parse_and_load_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13618: "get_writable_compiled_filename
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13620: "parse_and_load_cspm_file_into_specific_pl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13647: "generate_temporary_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13677: "eval_elapsed_time
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13694: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13694: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13697: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13700: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13991: "user: get_user_signal_ref
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13993: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14057: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14456: side
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14458: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14471: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14507: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14562: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14794: call and the implementation for reading the result from prolog
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14909: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14911: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15021: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15025: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15029: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15069: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15072: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15096: "tcltk_play_ltl_ctl_counterexample_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15112: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15115: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15127: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15128: b_get_definition_string_list_from_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15129: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15130: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15138: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15209: "ltl: parse_and_pp_ltl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15218: "ctl: parse_and_pp_ctl_formula
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15240: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15241: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15293: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15330: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15356: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15358: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15361: b_get_definition_string_list_from_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15364: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15400: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15406: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15409: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15429: [subst 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15465: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15556: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15573: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15580: bmachine:b_get_definition_string_from_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15582: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15582: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15636: bmachine:b_get_definition_string_from_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15685: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15690: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15782: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15797: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15803: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15821: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15825: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15889: "parsercall:get_java_fullversion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16022: "tcltk_save_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16035: "tcltk_load_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16055: "tcltk_save_specification_state_for_refinement
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16057: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16059: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16068: {bmachine:b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16090: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16092: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16166: {b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16249: tcltk_load_refine_spec_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16250: tcltk_refinement_search
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16257: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16284: "b_show_history:write_full_history_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16301: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16305: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16352: "tcltk_check_state_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16355: "tcltk_check_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16359: test_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16391: "b_machine_hierarchy:write_dot_hierarchy_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16403: "meta_interface:command_preferences_category
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16410: "meta_interface:call_dot_command
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16420: "meta_interface:command_preferences_category
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16428: "meta_interface:call_dot_command_for_expr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16451: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16454: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16456: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16466: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16470: "tcltk_print_states_for_dot_sfdp
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16486: "tcltk_print_neighbourhood_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16492: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16537: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16554: generate_dot_from_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16572: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16587: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16588: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16599: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16612: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16619: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16631: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16636: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16641: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16661: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16693: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16702: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16702: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16720: current_state_corresponds_to_fully_setup_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16730: initialised_b_state_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16744: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16755: "compute_covered_values_for_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16762: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16769: "tcltk_compute_nr_covered_values_for_all_variables
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16785: "tcltk_evaluate_expression_over_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16801: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16810: "tcltk_print_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16814: "state_custom_dot_graph:tcltk_generate_state_custom_dot_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16832: "tcltk_print_history_to_current_state_with_neighbors_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16848: "tcltk_print_shortest_trace_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16850: "tcltk_print_history_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16884: "state_space_reduction:tcltk_write_signature_merge_to_dotfile
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16901: "reduce_graph_state_space:print_subgraph_of_goal_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16903: "reduce_graph_state_space:print_subgraph_associated_with_invariant_violations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16917: "debug_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16918: "run_time_type_check_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16919: "trace_upon_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16954: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16955: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16963: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16970: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16976: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17001: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17003: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17070: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17074: b_write_machine_representation_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17090: "tcltk_print_states_for_spin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17099: "promela_save_as_neverclaim
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17141: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17142: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17144: tcltk_get_image_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17229: "tcltk_can_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17256: "tcltk_can_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17274: "tcltk_react_to_item_right_click
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17285: "tcltk_react_to_item_drag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17373: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17375: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17382: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17390: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17394: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17399: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17402: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17405: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17407: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17412: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17415: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17417: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17419: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17422: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17425: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17427: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17458: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17480: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17502: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17508: ic3:counter_example_can_be_replayed
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17524: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17542: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17543: "tcltk_unsat_core_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17553: query e
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17555: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17572: reduce_graph_state_space:get_alphabet_signatures
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17580: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17602: reduce_graph_state_space:assert_all_transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17603: reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17607: "reduce_graph_state_space:transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17625: which arguments we dont care about
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17631: "reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17656: "reduce_graph_state_space:assert_transition_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17667: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17675: reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17680: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17708: "reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17714: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17786: "(reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17793: "retractall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17805: reduce_graph_state_space:user_has_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17902: pathes:runtime_application_path
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17904: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17906: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17908: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17912: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17917: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17922: tcltk_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17937: tcltk_cbc_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17950: "tcltk_cbc_enabling_relations_after_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17953: "tcltk_cbc_enabling_relations_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17964: tcltk_cbc_simultaneous_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17971: tcltk_cbc_dependence_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17976: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17977: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17989: tcltk_operations_covered_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18001: "check_if_feasible_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18011: tcltk_compute_mcdc_operation_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18019: tcltk_compute_mcdc_invariant_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18027: tcltk_cbc_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18033: b_read_write_info:tcltk_read_write_matrix
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18040: tcltk_create_dependence_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18045: tcltk_create_enable_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18050: tcltk_create_enable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18055: tcltk_create_disable_graph_por
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18060: tcltk_dot_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18066: tcltk_disabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18086: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18329: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18332: prologTaskStart
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18352: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18359: prologTaskStep
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18368: prologTaskAbort
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18374: prologTaskFinish
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18375: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18386: Task 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18484: bvisual2:set_translation_mode
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:23: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:31: tcltk_tree_inspector:reset_tcltk_tree_inspector
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:49: tcltk_tree_inspector:tti_number_of_columns
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:64: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:83: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:132: tcltk_tree_inspector:tti_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:583: b_trace_checking:print_trace_as_fdr_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:914: analyze_hash_collisions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:991: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:993: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1082: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1083: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1092: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1094: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1094: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1096: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1096: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1100: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1102: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1105: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1107: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1109: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1111: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1640: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1642: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1721: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1736: preferences:clear_recent_documents 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2110: "preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2112: "eclipse_interface:ops_with_virtual_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2113: "eclipse_interface:ops_with_real_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2142: tcltk_mark_current_node_to_be_recomputed_wo_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2150: tcltk_mark_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2154: tcltk_finish_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2663: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2922: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5593: proz:startzconversiontests
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5691: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5694: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5738: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6034: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6126: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6593: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6642: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6673: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6718: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7648: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7653: tcltk_fast_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7837: tcltk_execute_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7873: tcltk_find_shortest_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7933: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7972: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7989: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7997: reset_to_defaults
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8011: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8012: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8039: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8071: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8075: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8077: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8479: tcltk_top_level_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8487: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8640: {Query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8740: tcltk_analyse
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8790: tcltk_analyse_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8801: tcltk_show_typing_of_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10075: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10401: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10579: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10653: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10908: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10909: preferences:reset_for_benchmarking
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10910: preferences:deactivate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10956: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10957: preferences:activate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11074: count_errors_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11077: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11207: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11429: tcltk_cbc_refinement_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11441: tcltk_constraint_based_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11748: tcltk_get_options_dest_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11788: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12432: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12536: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15767: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15769: host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15774: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15886: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15912: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15943: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15980: mc_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15996: symmetry_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16402: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16419: "command_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16860: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16922: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16930: "tcltk_turn_debugging_on
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16932: "tcltk_turn_debugging_off
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16935: "turn_on_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16937: "turn_off_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16940: "turn_trace_upon_error_on
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16941: "debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16944: "turn_trace_upon_error_off
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16945: "nodebug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16977: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17011: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17038: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17459: "bmc_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17481: "kinduction_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17503: "ic3_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17525: "ctigar_symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17689: "reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17695: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17776: reduce_graph_state_space:user_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17795: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17806: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17807: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17828: reduce_graph_state_space:user_made_arg_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17841: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18457: tcltk_set_initial_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:18468: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8387: tcltk_compute_coverage_and_enabling
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8390: tcltk_compute_coverage_and_degree
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8393: tcltk_compute_min_max
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8396: tcltk_get_vacuous_invariants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8401: tcltk_get_vacuous_guards
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8406: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8628: {Query
