% Prolog calls from tcl Files
:- module(tcltk_calls, [tcltk_call/4]).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl',12).
tcltk_call(tcltk_get_node_info,ast_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl',90).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',22).
tcltk_call(tcltk_bv_get_tops,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',86).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',125).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',132).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',139).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',147).
tcltk_call(tcltk_bv_get_unlimited_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',149).
tcltk_call(tcltk_bv_get_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',213).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',235).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',473).
tcltk_call(bv_print_to_file,bvisual2,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',476).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',485).
tcltk_call(bv_write_all_variables_and_constants,bvisual2,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',487).
tcltk_call(version,version,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',41).
tcltk_call(prolog_flag,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',44).
tcltk_call(revision,version,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',47).
tcltk_call(lastchangeddate,version,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',49).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',214).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',230).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',254).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',256).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',270).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',270).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',285).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',322).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',323).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',496).
tcltk_call(self_checks_exist,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',762).
tcltk_call(self_checks_exist,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',768).
tcltk_call(debug,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',790).
tcltk_call(print_normal_forms,b_normal_form,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',812).
tcltk_call(state_space_initialise_with_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',821).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',890).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',902).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',905).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',908).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',911).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',916).
tcltk_call(print_non_default_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',933).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',938).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',941).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',944).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',947).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',977).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',982).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1058).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1067).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1080).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1093).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1122).
tcltk_call(cspm_file_add_remove_unicode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1143).
tcltk_call(cspm_file_add_remove_unicode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1150).
tcltk_call(tcltk_eval,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1185).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1187).
tcltk_call(tcltk_show_expression_as_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1229).
tcltk_call(tcltk_eval_as_table,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1247).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1248).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1308).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1310).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1320).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1327).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1527).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1581).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1582).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1589).
tcltk_call(tcltk_can_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1752).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1758).
tcltk_call(tcltk_can_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1796).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1813).
tcltk_call(tcltk_has_eventtrace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1834).
tcltk_call(tcltk_show_eventtrace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1847).
tcltk_call(tcltk_get_detailed_state_error,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1859).
tcltk_call(can_generate_dot_from_last_state_error,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1864).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1891).
tcltk_call(ops_user_interrupt_occured,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1897).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1910).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1919).
tcltk_call(plugin_has_preferences,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1924).
tcltk_call(plugins_with_preferences,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1925).
tcltk_call(get_specification_description,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1943).
tcltk_call(get_specification_description,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1946).
tcltk_call(get_specification_description,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1949).
tcltk_call(plugin_is_available_for_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1962).
tcltk_call(available_plugins_for_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1963).
tcltk_call(start_plugin_for_current_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1981).
tcltk_call(plugin_has_output,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1994).
tcltk_call(plugin_get_output,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1997).
tcltk_call(plugin_get_output,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2009).
tcltk_call(stop_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2026).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2037).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2040).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2049).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2051).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2059).
tcltk_call(animation_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2093).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2120).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2139).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2142).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2312).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2328).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2348).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2350).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2352).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2353).
tcltk_call(animation_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2530).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2671).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2950).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2952).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',3143).
tcltk_call(environ,system,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',3358).
tcltk_call(tcltk_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5441).
tcltk_call(tcltk_goto_an_invariant_violation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5449).
tcltk_call(spec_file_has_been_successfully_loaded,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5470).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5481).
tcltk_call(perform_self_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5492).
tcltk_call(perform_verbose_self_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5505).
tcltk_call(get_module_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5518).
tcltk_call(perform_self_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5521).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5576).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5579).
tcltk_call(plugin_file_extensions,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5632).
tcltk_call(active_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5659).
tcltk_call(add_recent_document,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5665).
tcltk_call(unset_tcltk_cspm_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5679).
tcltk_call(is_plugin_file_extension,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5696).
tcltk_call(available_plugins_for_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5704).
tcltk_call(tcltk_load_packaged_eventb_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5732).
tcltk_call(b_show_machine_representation,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5736).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5793).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5799).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5802).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5806).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5810).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5813).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5816).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5819).
tcltk_call(tcltk_get_command_line_file_to_open,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5827).
tcltk_call(tcltk_get_command_line_tcltk_commands,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5834).
tcltk_call(tcltk_open_xtl_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5852).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5958).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5963).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5965).
tcltk_call(tcltk_open_z_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5986).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6008).
tcltk_call(load_prob_file,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6038).
tcltk_call(tcltk_open_b_file_for_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6039).
tcltk_call(set_animation_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6043).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6100).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6124).
tcltk_call(platform_is_64_bit,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6125).
tcltk_call(load_plugin_file,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6164).
tcltk_call(tcltk_open_promela_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6189).
tcltk_call(tcltk_open_cspm_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6217).
tcltk_call(set_tcltk_cspm_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6232).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6244).
tcltk_call(tcltk_add_csp_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6310).
tcltk_call(tcltk_open_b_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6369).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6496).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6498).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6532).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6558).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6578).
tcltk_call(tcl_plugin_syntax_colouring,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6579).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6600).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6628).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6632).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6637).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6640).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6646).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6651).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6655).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6663).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6676).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6680).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6686).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6692).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6699).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6703).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6711).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6717).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6725).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6750).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6753).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6757).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6762).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6767).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6771).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6775).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6779).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6788).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6791).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6795).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6799).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6803).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6815).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6818).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6823).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6828).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6832).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6837).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6842).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6847).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6857).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6860).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6865).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6869).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6874).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6878).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6882).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6891).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6894).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6899).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6905).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6911).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6916).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6927).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6949).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6978).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7015).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7016).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7019).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7022).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7025).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7028).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7031).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7034).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7037).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7072).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7107).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7119).
tcltk_call(write_values_to_file,b_show_history,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7129).
tcltk_call(add_recent_document,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7156).
tcltk_call(active_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7254).
tcltk_call(tcltk_prepare_for_reload,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7265).
tcltk_call(is_registered_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7280).
tcltk_call(tcltk_get_options,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7328).
tcltk_call(tcltk_random_perform,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7334).
tcltk_call(tcltk_random_perform,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7409).
tcltk_call(tcltk_current_state_invariant_violated,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7412).
tcltk_call(tcltk_execute_until,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7448).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7476).
tcltk_call(cli_prefs_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7533).
tcltk_call(save_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7534).
tcltk_call(save_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7536).
tcltk_call(save_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7539).
tcltk_call(tcltk_load_commandline_prefs_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7545).
tcltk_call(load_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7548).
tcltk_call(file_exists,file_systems,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7549).
tcltk_call(load_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7550).
tcltk_call(load_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7552).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7671).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7684).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7686).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7707).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7709).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7790).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7791).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7800).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7801).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7802).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7803).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7804).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7805).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7815).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7815).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7816).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7816).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7817).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7818).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7825).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7833).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7937).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7940).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7969).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7970).
tcltk_call(model_checking_is_incomplete,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7974).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8033).
tcltk_call(tcltk_unique_top_level_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8034).
tcltk_call(current_state_corresponds_to_setup_constants_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8039).
tcltk_call(b_machine_has_constants_or_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8140).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8140).
tcltk_call(b_get_machine_operation_parameter_names,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8147).
tcltk_call(tcltk_add_user_executed_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8211).
tcltk_call(query,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8223).
tcltk_call(interruptable_call,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8224).
tcltk_call(query,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8234).
tcltk_call(interruptable_call,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8291).
tcltk_call(tcltk_analyse_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8324).
tcltk_call(b_reset_machine_goal_from_DEFINITIONS,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8350).
tcltk_call(tcltk_show_current_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8376).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8522).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8526).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8535).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8544).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8545).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8553).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8585).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8587).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8592).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8606).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8610).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8636).
tcltk_call(ensure_console_parser_launched,parsercall,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8639).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8737).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8809).
tcltk_call(last_expression_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8815).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8823).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8845).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8854).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8863).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8883).
tcltk_call(tcltk_eval,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8969).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8975).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8978).
tcltk_call(interruptable_tcltk_eval,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8996).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9002).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9007).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9045).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9181).
tcltk_call(popup,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9182).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9190).
tcltk_call(tcltk_get_specialized_invariants_for_ops,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9191).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9199).
tcltk_call(tcltk_get_specialized_invariant_for_op,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9203).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9213).
tcltk_call(tcltk_before_after_predicate_for_operation,before_after_predicates,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9217).
tcltk_call(tcltk_load_constants,value_persistance,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9227).
tcltk_call(tcltk_get_profile_info,runtime_profiler,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9237).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9254).
tcltk_call(model_checking_is_incomplete,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9259).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9319).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9342).
tcltk_call(tcltk_get_constants_predicate,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9343).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9351).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9353).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9354).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9360).
tcltk_call(b_write_eventb_machine_to_classicalb_to_file,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9364).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9557).
tcltk_call(tcltk_machine_has_assertions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9583).
tcltk_call(b_get_machine_goal,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9592).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9647).
tcltk_call(tcltk_get_constants_predicate,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9648).
tcltk_call(tcltk_dbf_modes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9716).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9725).
tcltk_call(b_get_machine_goal,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9737).
tcltk_call(tcltk_machine_has_assertions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9746).
tcltk_call(operation_name_not_yet_covered,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9753).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9759).
tcltk_call(tcltk_state_space_only_has_root_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9796).
tcltk_call(tcltk_search_among_existing_nodes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9804).
tcltk_call(tcltk_set_dbf_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9829).
tcltk_call(prolog_flag,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9844).
tcltk_call(nl,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9846).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9847).
tcltk_call(statistics,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9868).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9870).
tcltk_call(tcltk_find_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9874).
tcltk_call(operation_name_not_yet_covered,state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9879).
tcltk_call(proof_info_model_checking_incomplete,model_checker,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9882).
tcltk_call(time_out_for_invariant,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9885).
tcltk_call(tcltk_hash_model_checking_imprecise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9889).
tcltk_call(state_error_exists,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9896).
tcltk_call(tcltk_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9947).
tcltk_call(cbc_get_uncovered_events,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10045).
tcltk_call(tcl_get_stored_test_cases,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10049).
tcltk_call(tcl_execute_stored_test_case,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10071).
tcltk_call(tcl_generate_testcases,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10091).
tcltk_call(tcl_create_local_testsuite,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10212).
tcltk_call(set_unicode_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10294).
tcltk_call(get_internal_representation,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10295).
tcltk_call(unset_unicode_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10302).
tcltk_call(tcltk_get_unsat_core_with_types,predicate_debugger,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10306).
tcltk_call(b_show_eventb_as_classicalb,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10313).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10391).
tcltk_call(b_set_machine_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10402).
tcltk_call(get_error_span_linecol,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10409).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10412).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10423).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10431).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10436).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10457).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10462).
tcltk_call(tcltk_goto_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10482).
tcltk_call(tcltk_goto_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10490).
tcltk_call(tcltk_goto_a_non_resetable_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10499).
tcltk_call(tcltk_goto_a_non_deterministic_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10508).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10515).
tcltk_call(tcltk_goto_node_with_id,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10518).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10527).
tcltk_call(tcltk_goto_a_branching_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10536).
tcltk_call(tcltk_search_among_existing_nodes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10549).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10555).
tcltk_call(tcltk_goto_event_list_property_violation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10601).
tcltk_call(get_selected_events,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10605).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10606).
tcltk_call(tcltk_goto_state_enabling_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10621).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10624).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10649).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10651).
tcltk_call(ltl_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10678).
tcltk_call(ctl_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10718).
tcltk_call(max_nr_of_new_nodes_limit_not_reached,state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10724).
tcltk_call(max_nr_of_new_nodes_limit_not_reached,state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10730).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10762).
tcltk_call(tcltk_cbc_find_trace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10763).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10773).
tcltk_call(tcltk_constraint_find_valid_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10778).
tcltk_call(tcltk_constraint_find_valid_state_with_goal_pred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10784).
tcltk_call(tcltk_perform_cbc_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10799).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10815).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10823).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10828).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10833).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10840).
tcltk_call(tcltk_constraint_based_check_op,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10841).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10855).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10859).
tcltk_call(tcltk_constraint_find_deadlock_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10860).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10873).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10878).
tcltk_call(tcltk_constraint_find_deadlock_state_with_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10879).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10892).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10897).
tcltk_call(tcltk_constraint_find_static_assertion_violation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10898).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10918).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10922).
tcltk_call(unfixed_deferred_set,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10922).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11017).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11051).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11058).
tcltk_call(bmachine_is_precompiled,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11123).
tcltk_call(tcltk_no_constants_or_no_inititalisation_found,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11123).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11124).
tcltk_call(b_machine_has_constants_or_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11125).
tcltk_call(tcltk_current_node_has_no_real_transition,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11154).
tcltk_call(bmachine_is_precompiled,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11156).
tcltk_call(b_machine_has_constants_or_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11156).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11156).
tcltk_call(tcltk_current_node_has_partial_transition,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11158).
tcltk_call(preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11159).
tcltk_call(tcltk_unsatisfiable_components_exist,b_interpreter,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11180).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11196).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11196).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11201).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11207).
tcltk_call(tcltk_quick_describe_unsat_properties,b_interpreter,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11218).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11229).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11238).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11249).
tcltk_call(get_csp_processes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11261).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11298).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11338).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11342).
tcltk_call(tcltk_can_backtrack,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11374).
tcltk_call(tcltk_can_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11381).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11394).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11422).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11442).
tcltk_call(tcltk_get_line_col,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11473).
tcltk_call(tcltk_is_sync_event,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11484).
tcltk_call(tcltk_backtrack,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11509).
tcltk_call(tcltk_no_constants_or_no_inititalisation_found,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11523).
tcltk_call(tcltk_perform_nr,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11528).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11540).
tcltk_call(tcltk_backtrack,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11550).
tcltk_call(tcltk_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11555).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11581).
tcltk_call(get_cbc_data_base_id_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11736).
tcltk_call(get_cbc_data_base_text_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11736).
tcltk_call(tcltk_constraint_based_check_op,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11944).
tcltk_call(tcltk_cbc_find_trace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11948).
tcltk_call(tcltk_constraint_find_deadlock_state_with_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11952).
tcltk_call(assert_real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11955).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11961).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11963).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11979).
tcltk_call(tcltk_perform_cbc_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11985).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12033).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12055).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12093).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12134).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12186).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12248).
tcltk_call(get_csp_processes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12427).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12503).
tcltk_call(get_csp_assertions_as_string,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12514).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12624).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12640).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12642).
tcltk_call(get_csp_processes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12673).
tcltk_call(get_ltl_formulas_from_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12907).
tcltk_call(parse_and_load_cspm_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12924).
tcltk_call(get_writable_compiled_filename,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12965).
tcltk_call(parse_and_load_cspm_file_into_specific_pl_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12967).
tcltk_call(generate_temporary_cspm_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12991).
tcltk_call(eval_elapsed_time,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13021).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13038).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13041).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13044).
tcltk_call(user,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13302).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13304).
tcltk_call(tcltk_check_csp_assertion,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13366).
tcltk_call(side,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13764).
tcltk_call(tcltk_check_csp_assertion,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13766).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13779).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13815).
tcltk_call(get_csp_assertions_as_string,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13870).
tcltk_call(call,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14102).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14217).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14219).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14329).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14333).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14337).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14377).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14380).
tcltk_call(tcltk_play_ltl_ctl_counterexample_trace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14404).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14415).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14418).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14431).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14439).
tcltk_call(ltl,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14510).
tcltk_call(ctl,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14519).
tcltk_call(ltl_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14628).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14654).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14701).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14704).
tcltk_call('[subst',undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14724).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14760).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14850).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14867).
tcltk_call(b_get_definition_string_from_machine,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14874).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14876).
tcltk_call(get_formulas_from_cspm_file,haskell_csp,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14876).
tcltk_call(b_get_definition_string_from_machine,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14930).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14979).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14984).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15076).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15091).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15097).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15115).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15119).
tcltk_call(tcltk_save_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15311).
tcltk_call(tcltk_load_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15324).
tcltk_call(tcltk_save_specification_state_for_refinement,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15344).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15346).
tcltk_call(tcltk_find_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15348).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15379).
tcltk_call(tcltk_find_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15381).
tcltk_call(tcltk_load_refine_spec_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15538).
tcltk_call(tcltk_refinement_search,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15539).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15546).
tcltk_call(write_history_to_file,b_show_history,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15573).
tcltk_call(tcltk_save_history_as_trace_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15590).
tcltk_call(tcltk_save_history_as_trace_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15594).
tcltk_call(tcltk_check_state_sequence_from_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15641).
tcltk_call(tcltk_check_sequence_from_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15644).
tcltk_call(test_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15648).
tcltk_call(write_dot_hierarchy_to_file,b_machine_hierarchy,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15677).
tcltk_call(write_dot_event_hierarchy_to_file,b_machine_hierarchy,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15682).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15698).
tcltk_call(tcltk_print_states_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15700).
tcltk_call(tcltk_print_states_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15707).
tcltk_call(tcltk_print_neighbourhood_states_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15723).
tcltk_call(b_reset_machine_goal_from_DEFINITIONS,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15729).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15774).
tcltk_call(generate_dot_from_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15781).
tcltk_call(generate_dot_from_assertions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15783).
tcltk_call(generate_dot_from_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15785).
tcltk_call(generate_dot_from_deadlock_po,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15787).
tcltk_call(generate_dot_from_last_span_predicate,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15789).
tcltk_call(generate_dot_from_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15791).
tcltk_call(generate_dot_from_invariant,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15793).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15808).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15809).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15820).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15833).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15840).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15850).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15855).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15860).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15880).
tcltk_call(write_transition_diagram_for_expr_to_dotfile,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15898).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15915).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15933).
tcltk_call(initialised_b_state_exists,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15943).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15957).
tcltk_call(compute_covered_values_for_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15968).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15975).
tcltk_call(tcltk_compute_nr_covered_values_for_all_variables,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15982).
tcltk_call(tcltk_evaluate_expression_over_history,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15998).
tcltk_call(tcltk_print_current_state_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16019).
tcltk_call(tcltk_generate_state_custom_dot_graph,state_custom_dot_graph,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16023).
tcltk_call(tcltk_print_current_state_as_graph_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16027).
tcltk_call(print_cstate_graph,graph_canon,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16028).
tcltk_call(tcltk_print_shortest_trace_to_current_state_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16046).
tcltk_call(tcltk_print_history_to_current_state_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16048).
tcltk_call(print_dot_for_dfa_from_nfa,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16080).
tcltk_call(tcltk_write_signature_merge_to_dotfile,state_space_reduction,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16082).
tcltk_call(reduce_graph_state_space,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16099).
tcltk_call(print_subgraph_associated_with_invariant_violations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16101).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16115).
tcltk_call(create_enable_graph,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16122).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16134).
tcltk_call(create_enable_graphs,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16141).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16154).
tcltk_call(print_base_guide,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16161).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16174).
tcltk_call(print_event_guide,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16185).
tcltk_call(debug_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16203).
tcltk_call(run_time_type_check_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16204).
tcltk_call(trace_upon_error,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16205).
tcltk_call(tcltk_print_states_for_fdr,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16240).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16241).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16249).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16256).
tcltk_call(tcltk_print_states_for_fdr,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16262).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16287).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16289).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16347).
tcltk_call(b_write_machine_representation_to_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16351).
tcltk_call(tcltk_print_states_for_spin,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16367).
tcltk_call(promela_save_as_neverclaim,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16376).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16402).
tcltk_call(tcltk_get_image_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16403).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16541).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16543).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16550).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16558).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16562).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16567).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16570).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16573).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16575).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16580).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16583).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16585).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16587).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16590).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16593).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16595).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16626).
tcltk_call(counter_example_can_be_replayed,symbolic_model_checker,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16632).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16649).
tcltk_call(tcltk_unsat_core_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16650).
tcltk_call(query,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16660).
tcltk_call(desired_user_transition,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16686).
tcltk_call(transition_arg_dont_cares,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16711).
tcltk_call(which,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16729).
tcltk_call(get_transition_arguments_from_source,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16735).
tcltk_call(assert_transition_dont_cares,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16760).
tcltk_call(desired_user_transition,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16771).
tcltk_call(use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16779).
tcltk_call(use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16784).
tcltk_call(use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16812).
tcltk_call(use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16818).
tcltk_call(retractall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16897).
tcltk_call(user_has_made_op_selection,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16909).
tcltk_call(runtime_application_path,pathes,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17006).
tcltk_call(absolute_file_name,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17008).
tcltk_call(absolute_file_name,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17010).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17012).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17016).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17021).
tcltk_call(tcltk_enabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17026).
tcltk_call(tcltk_cbc_enabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17041).
tcltk_call(tcltk_cbc_simultaneous_enabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17049).
tcltk_call(tcltk_cbc_dependence_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17056).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17061).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17062).
tcltk_call(tcltk_operations_covered_info,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17074).
tcltk_call(tcltk_compute_mcdc_operation_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17082).
tcltk_call(tcltk_compute_mcdc_invariant_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17090).
tcltk_call(tcltk_cbc_cfg_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17098).
tcltk_call(tcltk_disabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17122).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17383).
tcltk_call(prologTaskStart,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17386).
tcltk_call(walltime,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17406).
tcltk_call(prologTaskStep,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17413).
tcltk_call(prologTaskAbort,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17422).
tcltk_call(prologTaskFinish,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17428).
tcltk_call(walltime,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17429).
tcltk_call('Task',undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17440).
tcltk_call(set_translation_mode,bvisual2,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17537).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',12).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',23).
tcltk_call(reset_tcltk_tree_inspector,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',31).
tcltk_call(tti_number_of_columns,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',49).
tcltk_call(tti_column_info,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',64).
tcltk_call(tti_column_info,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',83).
tcltk_call(tti_get_node_info,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',132).
tcltk_call(print_trace_as_fdr_check,b_trace_checking,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',532).
tcltk_call(analyze_hash_collisions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',829).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',896).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',898).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',990).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',991).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1000).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1002).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1002).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1004).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1004).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1008).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1010).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1013).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1015).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1017).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1019).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1413).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1415).
tcltk_call(get_recent_documents,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1494).
tcltk_call(clear_recent_documents,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1509).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1874).
tcltk_call(ops_with_virtual_timeout,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1876).
tcltk_call(ops_with_real_timeout,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1877).
tcltk_call(tcltk_mark_current_node_to_be_recomputed_wo_timeout,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1906).
tcltk_call(tcltk_mark_current_node_to_be_recomputed_with_random_enum,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1914).
tcltk_call(tcltk_finish_current_node_to_be_recomputed_with_random_enum,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1918).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2399).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2661).
tcltk_call(startzconversiontests,proz,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5309).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5407).
tcltk_call(tcltk_compute_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5410).
tcltk_call(tcltk_compute_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5454).
tcltk_call(tcltk_clear_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5729).
tcltk_call(get_recent_documents,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5820).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6267).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6316).
tcltk_call(tcltk_clear_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6347).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6392).
tcltk_call(tcltk_reset,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7313).
tcltk_call(tcltk_fast_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7318).
tcltk_call(tcltk_execute_trace_to_current_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7467).
tcltk_call(tcltk_find_shortest_trace_to_current_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7503).
tcltk_call(backup_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7563).
tcltk_call(get_preferences_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7602).
tcltk_call(revert_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7618).
tcltk_call(reset_to_defaults,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7626).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7638).
tcltk_call(get_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7639).
tcltk_call(get_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7666).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7698).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7702).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7704).
tcltk_call(tcltk_top_level_operations,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8073).
tcltk_call(findall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8081).
tcltk_call(tcltk_analyse,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8326).
tcltk_call(tcltk_analyse_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8357).
tcltk_call(tcltk_show_typing_of_variables_and_constants,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8368).
tcltk_call(tcltk_reset,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9522).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9836).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10011).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10077).
tcltk_call(backup_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10326).
tcltk_call(reset_for_benchmarking,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10327).
tcltk_call(deactivate_recent_documents,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10328).
tcltk_call(revert_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10373).
tcltk_call(activate_recent_documents,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10374).
tcltk_call(count_errors_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10467).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10470).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10595).
tcltk_call(tcltk_cbc_refinement_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10817).
tcltk_call(tcltk_constraint_based_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10829).
tcltk_call(tcltk_get_options_dest_info,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11108).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11146).
tcltk_call(findall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11774).
tcltk_call(findall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11878).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15061).
tcltk_call(host_platform,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15063).
tcltk_call(get_preferences_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15068).
tcltk_call(prob_licence,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15180).
tcltk_call(prob_licence,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15201).
tcltk_call(mc_summary,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15269).
tcltk_call(symmetry_summary,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15285).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16058).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16208).
tcltk_call(tcltk_turn_debugging_on,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16216).
tcltk_call(tcltk_turn_debugging_off,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16218).
tcltk_call(turn_on_run_time_type_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16221).
tcltk_call(turn_off_run_time_type_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16223).
tcltk_call(turn_trace_upon_error_on,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16226).
tcltk_call(debug,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16227).
tcltk_call(turn_trace_upon_error_off,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16230).
tcltk_call(nodebug,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16231).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16263).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16297).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16315).
tcltk_call(symbolic_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16627).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16793).
tcltk_call(set_use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16799).
tcltk_call(user_made_op_selection,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16880).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16899).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16910).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16911).
tcltk_call(user_made_arg_selection,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16932).
tcltk_call(set_use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16945).
tcltk_call(tcltk_set_initial_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17510).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17521).
