% Prolog calls from tcl Files
:- module(tcltk_calls, [tcltk_call/4]).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl',12).
tcltk_call(tcltk_get_node_info,ast_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl',90).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',22).
tcltk_call(tcltk_bv_get_tops,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',86).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',125).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',132).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',139).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',147).
tcltk_call(tcltk_bv_get_unlimited_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',149).
tcltk_call(tcltk_bv_get_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',213).
tcltk_call(tcltk_bv_get_structure,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',235).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',473).
tcltk_call(bv_print_to_file,bvisual2,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',476).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',485).
tcltk_call(bv_write_all_variables_and_constants,bvisual2,'/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl',487).
tcltk_call(version,version,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',41).
tcltk_call(prolog_flag,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',44).
tcltk_call(revision,version,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',47).
tcltk_call(lastchangeddate,version,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',49).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',214).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',230).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',254).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',256).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',270).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',270).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',285).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',322).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',323).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',498).
tcltk_call(self_checks_exist,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',764).
tcltk_call(self_checks_exist,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',770).
tcltk_call(debug,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',793).
tcltk_call(print_normal_forms,b_normal_form,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',815).
tcltk_call(nl,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',821).
tcltk_call(state_space_initialise_with_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',824).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',893).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',905).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',908).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',911).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',914).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',919).
tcltk_call(print_non_default_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',936).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',941).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',944).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',947).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',950).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',980).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',985).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1061).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1070).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1083).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1096).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1125).
tcltk_call(cspm_file_add_remove_unicode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1146).
tcltk_call(cspm_file_add_remove_unicode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1153).
tcltk_call(tcltk_eval,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1188).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1190).
tcltk_call(tcltk_show_expression_as_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1232).
tcltk_call(tcltk_eval_as_table,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1250).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1251).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1311).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1313).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1334).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1352).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1564).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1618).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1619).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1626).
tcltk_call(tcltk_can_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1789).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1795).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1799).
tcltk_call(tcltk_can_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1833).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1850).
tcltk_call(tcltk_has_eventtrace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1872).
tcltk_call(tcltk_show_eventtrace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1885).
tcltk_call(tcltk_get_detailed_state_error,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1897).
tcltk_call(can_generate_dot_from_last_state_error,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1902).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1929).
tcltk_call(ops_user_interrupt_occured,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1935).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1948).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1957).
tcltk_call(plugin_has_preferences,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1962).
tcltk_call(plugins_with_preferences,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1963).
tcltk_call(get_specification_description,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1981).
tcltk_call(get_specification_description,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1984).
tcltk_call(get_specification_description,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1987).
tcltk_call(plugin_is_available_for_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2000).
tcltk_call(available_plugins_for_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2001).
tcltk_call(start_plugin_for_current_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2019).
tcltk_call(plugin_has_output,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2032).
tcltk_call(plugin_get_output,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2035).
tcltk_call(plugin_get_output,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2047).
tcltk_call(stop_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2064).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2075).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2078).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2087).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2089).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2097).
tcltk_call(animation_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2131).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2158).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2177).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2180).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2350).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2366).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2386).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2388).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2390).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2391).
tcltk_call(animation_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2568).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2709).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2988).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2990).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',3181).
tcltk_call(environ,system,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',3396).
tcltk_call(tcltk_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5479).
tcltk_call(tcltk_goto_an_invariant_violation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5487).
tcltk_call(spec_file_has_been_successfully_loaded,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5508).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5519).
tcltk_call(perform_self_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5530).
tcltk_call(perform_verbose_self_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5543).
tcltk_call(get_module_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5556).
tcltk_call(perform_self_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5559).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5614).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5617).
tcltk_call(plugin_file_extensions,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5670).
tcltk_call(active_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5697).
tcltk_call(add_recent_document,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5703).
tcltk_call(unset_tcltk_cspm_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5717).
tcltk_call(is_plugin_file_extension,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5734).
tcltk_call(available_plugins_for_mode,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5742).
tcltk_call(tcltk_load_packaged_eventb_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5770).
tcltk_call(b_show_machine_representation,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5774).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5831).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5837).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5840).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5844).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5848).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5851).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5854).
tcltk_call(tcltk_get_command_line_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5857).
tcltk_call(tcltk_get_command_line_file_to_open,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5865).
tcltk_call(tcltk_get_command_line_tcltk_commands,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5872).
tcltk_call(tcltk_open_xtl_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5890).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5996).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6001).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6003).
tcltk_call(tcltk_open_z_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6024).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6046).
tcltk_call(load_prob_file,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6073).
tcltk_call(tcltk_open_b_file_for_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6074).
tcltk_call(set_animation_minor_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6078).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6135).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6159).
tcltk_call(platform_is_64_bit,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6160).
tcltk_call(load_plugin_file,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6199).
tcltk_call(tcltk_open_promela_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6224).
tcltk_call(tcltk_open_cspm_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6252).
tcltk_call(set_tcltk_cspm_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6267).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6279).
tcltk_call(tcltk_add_csp_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6345).
tcltk_call(tcltk_open_b_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6404).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6531).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6533).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6567).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6593).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6613).
tcltk_call(tcl_plugin_syntax_colouring,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6614).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6635).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6663).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6667).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6672).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6675).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6681).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6686).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6690).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6698).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6711).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6715).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6721).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6727).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6734).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6738).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6746).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6752).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6760).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6785).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6788).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6792).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6797).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6802).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6806).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6810).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6814).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6824).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6827).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6831).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6835).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6839).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6851).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6854).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6859).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6864).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6868).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6873).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6878).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6883).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6893).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6896).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6901).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6905).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6910).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6914).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6918).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6927).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6930).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6935).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6941).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6947).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6952).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6963).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6985).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7014).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7051).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7052).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7055).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7058).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7061).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7064).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7067).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7070).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7073).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7108).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7143).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7155).
tcltk_call(write_values_to_file,b_show_history,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7165).
tcltk_call(add_recent_document,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7192).
tcltk_call(active_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7290).
tcltk_call(tcltk_prepare_for_reload,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7301).
tcltk_call(is_registered_plugin,plugins,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7316).
tcltk_call(tcltk_get_options,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7364).
tcltk_call(tcltk_random_perform,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7370).
tcltk_call(tcltk_random_perform,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7445).
tcltk_call(tcltk_current_state_invariant_violated,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7448).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7457).
tcltk_call(tcltk_execute_until,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7484).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7512).
tcltk_call(cli_prefs_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7569).
tcltk_call(save_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7570).
tcltk_call(save_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7572).
tcltk_call(save_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7575).
tcltk_call(tcltk_load_commandline_prefs_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7581).
tcltk_call(load_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7584).
tcltk_call(file_exists,file_systems,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7585).
tcltk_call(load_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7586).
tcltk_call(load_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7588).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7707).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7720).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7722).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7743).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7745).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7826).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7827).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7836).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7837).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7838).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7839).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7840).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7841).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7851).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7851).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7852).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7852).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7853).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7854).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7861).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7869).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7973).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7976).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8005).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8006).
tcltk_call(model_checking_is_incomplete,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8010).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8069).
tcltk_call(tcltk_unique_top_level_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8070).
tcltk_call(current_state_corresponds_to_setup_constants_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8075).
tcltk_call(b_machine_has_constants_or_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8176).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8176).
tcltk_call(b_get_machine_operation_parameter_names,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8183).
tcltk_call(tcltk_add_user_executed_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8247).
tcltk_call(query,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8259).
tcltk_call(interruptable_call,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8260).
tcltk_call(query,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8270).
tcltk_call(interruptable_call,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8327).
tcltk_call(tcltk_analyse_option,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8360).
tcltk_call(b_reset_machine_goal_from_DEFINITIONS,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8386).
tcltk_call(tcltk_show_current_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8412).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8558).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8562).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8571).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8580).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8581).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8589).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8621).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8623).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8628).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8642).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8646).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8672).
tcltk_call(ensure_console_parser_launched,parsercall,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8675).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8773).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8845).
tcltk_call(last_expression_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8851).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8859).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8881).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8890).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8899).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8919).
tcltk_call(tcltk_eval,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9005).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9011).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9014).
tcltk_call(interruptable_tcltk_eval,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9032).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9038).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9043).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9081).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9217).
tcltk_call(popup,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9218).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9226).
tcltk_call(tcltk_get_specialized_invariants_for_ops,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9227).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9235).
tcltk_call(tcltk_get_specialized_invariant_for_op,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9239).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9249).
tcltk_call(tcltk_before_after_predicate_for_operation,before_after_predicates,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9253).
tcltk_call(tcltk_load_constants,value_persistance,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9263).
tcltk_call(tcltk_get_profile_info,runtime_profiler,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9273).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9290).
tcltk_call(model_checking_is_incomplete,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9295).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9355).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9378).
tcltk_call(tcltk_get_constants_predicate,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9379).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9387).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9389).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9390).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9396).
tcltk_call(b_write_eventb_machine_to_classicalb_to_file,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9400).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9593).
tcltk_call(tcltk_machine_has_assertions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9619).
tcltk_call(b_get_machine_goal,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9628).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9683).
tcltk_call(tcltk_get_constants_predicate,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9684).
tcltk_call(tcltk_dbf_modes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9752).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9761).
tcltk_call(b_get_machine_goal,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9773).
tcltk_call(tcltk_machine_has_assertions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9782).
tcltk_call(operation_name_not_yet_covered,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9789).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9795).
tcltk_call(tcltk_state_space_only_has_root_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9832).
tcltk_call(tcltk_search_among_existing_nodes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9840).
tcltk_call(tcltk_set_dbf_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9865).
tcltk_call(prolog_flag,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9880).
tcltk_call(nl,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9882).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9883).
tcltk_call(statistics,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9904).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9906).
tcltk_call(tcltk_find_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9910).
tcltk_call(operation_name_not_yet_covered,state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9915).
tcltk_call(proof_info_model_checking_incomplete,model_checker,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9918).
tcltk_call(time_out_for_invariant,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9921).
tcltk_call(tcltk_hash_model_checking_imprecise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9925).
tcltk_call(state_error_exists,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9932).
tcltk_call(tcltk_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9983).
tcltk_call(cbc_get_uncovered_events,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10081).
tcltk_call(tcl_get_stored_test_cases,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10085).
tcltk_call(tcl_execute_stored_test_case,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10107).
tcltk_call(tcl_generate_testcases,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10127).
tcltk_call(tcl_create_local_testsuite,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10248).
tcltk_call(set_unicode_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10331).
tcltk_call(get_internal_representation,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10334).
tcltk_call(unset_unicode_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10342).
tcltk_call(tcltk_get_unsat_core_with_types,predicate_debugger,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10348).
tcltk_call(b_show_eventb_as_classicalb,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10355).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10433).
tcltk_call(b_set_machine_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10444).
tcltk_call(get_error_span_linecol,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10451).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10454).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10465).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10473).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10478).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10499).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10504).
tcltk_call(tcltk_goto_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10524).
tcltk_call(tcltk_goto_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10532).
tcltk_call(tcltk_goto_a_non_resetable_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10541).
tcltk_call(tcltk_goto_a_non_deterministic_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10550).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10557).
tcltk_call(tcltk_goto_node_with_id,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10560).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10569).
tcltk_call(tcltk_goto_a_branching_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10578).
tcltk_call(tcltk_search_among_existing_nodes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10591).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10597).
tcltk_call(tcltk_goto_event_list_property_violation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10643).
tcltk_call(get_selected_events,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10647).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10648).
tcltk_call(tcltk_goto_state_enabling_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10663).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10666).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10691).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10693).
tcltk_call(ltl_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10720).
tcltk_call(ctl_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10760).
tcltk_call(max_nr_of_new_nodes_limit_not_reached,state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10766).
tcltk_call(max_nr_of_new_nodes_limit_not_reached,state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10772).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10804).
tcltk_call(tcltk_cbc_find_trace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10805).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10815).
tcltk_call(tcltk_constraint_find_valid_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10820).
tcltk_call(tcltk_constraint_find_valid_state_with_goal_pred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10826).
tcltk_call(tcltk_perform_cbc_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10841).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10857).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10865).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10870).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10875).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10882).
tcltk_call(tcltk_constraint_based_check_op,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10883).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10897).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10901).
tcltk_call(tcltk_constraint_find_deadlock_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10902).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10915).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10920).
tcltk_call(tcltk_constraint_find_deadlock_state_with_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10921).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10934).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10939).
tcltk_call(tcltk_constraint_find_static_assertion_violation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10940).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10960).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10964).
tcltk_call(unfixed_deferred_set,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10964).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11060).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11094).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11101).
tcltk_call(tcltk_get_options,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11138).
tcltk_call(bmachine_is_precompiled,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11166).
tcltk_call(tcltk_no_constants_or_no_inititalisation_found,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11166).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11167).
tcltk_call(b_machine_has_constants_or_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11168).
tcltk_call(tcltk_current_node_has_no_real_transition,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11197).
tcltk_call(bmachine_is_precompiled,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11199).
tcltk_call(b_machine_has_constants_or_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11199).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11199).
tcltk_call(tcltk_current_node_has_partial_transition,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11201).
tcltk_call(preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11202).
tcltk_call(tcltk_unsatisfiable_components_exist,b_interpreter,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11223).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11239).
tcltk_call(current_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11239).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11244).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11250).
tcltk_call(tcltk_quick_describe_unsat_properties,b_interpreter,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11261).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11272).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11277).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11279).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11280).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11281).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11292).
tcltk_call(get_csp_processes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11304).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11341).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11365).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11381).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11385).
tcltk_call(tcltk_can_backtrack,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11417).
tcltk_call(tcltk_can_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11424).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11437).
tcltk_call(tcltk_get_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11449).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11465).
tcltk_call(tcltk_get_state_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11471).
tcltk_call(and,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11485).
tcltk_call(tcltk_get_history,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11491).
tcltk_call(tcltk_get_line_col,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11516).
tcltk_call(tcltk_is_sync_event,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11527).
tcltk_call(tcltk_backtrack,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11552).
tcltk_call(tcltk_no_constants_or_no_inititalisation_found,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11566).
tcltk_call(tcltk_perform_nr,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11571).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11583).
tcltk_call(tcltk_backtrack,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11593).
tcltk_call(tcltk_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11598).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11624).
tcltk_call(get_cbc_data_base_id_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11779).
tcltk_call(get_cbc_data_base_text_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11779).
tcltk_call(tcltk_constraint_based_check_op,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11987).
tcltk_call(tcltk_cbc_find_trace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11991).
tcltk_call(tcltk_constraint_find_deadlock_state_with_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11995).
tcltk_call(assert_real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11998).
tcltk_call(temporary_set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12004).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12006).
tcltk_call(reset_temporary_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12022).
tcltk_call(tcltk_perform_cbc_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12028).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12076).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12098).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12136).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12177).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12229).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12291).
tcltk_call(get_csp_processes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12470).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12543).
tcltk_call(get_csp_assertions_as_string,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12554).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12664).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12680).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12682).
tcltk_call(get_csp_processes,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12713).
tcltk_call(get_ltl_formulas_from_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12947).
tcltk_call(parse_and_load_cspm_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',12964).
tcltk_call(get_writable_compiled_filename,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13005).
tcltk_call(parse_and_load_cspm_file_into_specific_pl_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13007).
tcltk_call(generate_temporary_cspm_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13031).
tcltk_call(eval_elapsed_time,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13061).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13078).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13081).
tcltk_call(reset_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13084).
tcltk_call(user,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13371).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13373).
tcltk_call(tcltk_check_csp_assertion,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13437).
tcltk_call(side,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13836).
tcltk_call(tcltk_check_csp_assertion,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13838).
tcltk_call(real_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13851).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13887).
tcltk_call(get_csp_assertions_as_string,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',13942).
tcltk_call(call,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14174).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14289).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14291).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14401).
tcltk_call(set_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14405).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14409).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14449).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14452).
tcltk_call(tcltk_play_ltl_ctl_counterexample_trace,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14476).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14487).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14490).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14503).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14511).
tcltk_call(ltl,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14582).
tcltk_call(ctl,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14591).
tcltk_call(ltl_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14700).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14726).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14773).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14776).
tcltk_call('[subst',undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14796).
tcltk_call(assert_cli_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14832).
tcltk_call(add_element_to_history,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14922).
tcltk_call(get_history_elements_list,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14939).
tcltk_call(b_get_definition_string_from_machine,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14946).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14948).
tcltk_call(get_formulas_from_cspm_file,haskell_csp,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',14948).
tcltk_call(b_get_definition_string_from_machine,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15002).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15051).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15056).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15148).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15163).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15169).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15187).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15191).
tcltk_call(tcltk_save_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15383).
tcltk_call(tcltk_load_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15396).
tcltk_call(tcltk_save_specification_state_for_refinement,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15416).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15418).
tcltk_call(tcltk_find_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15420).
tcltk_call(b_get_machine_refinement_hierarchy,bmachine,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15429).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15451).
tcltk_call(tcltk_find_max_reached_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15453).
tcltk_call(b_get_machine_refinement_hierarchy,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15527).
tcltk_call(tcltk_load_refine_spec_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15610).
tcltk_call(tcltk_refinement_search,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15611).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15618).
tcltk_call(write_history_to_file,b_show_history,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15645).
tcltk_call(tcltk_save_history_as_trace_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15662).
tcltk_call(tcltk_save_history_as_trace_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15666).
tcltk_call(tcltk_check_state_sequence_from_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15713).
tcltk_call(tcltk_check_sequence_from_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15716).
tcltk_call(test_error_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15720).
tcltk_call(write_dot_hierarchy_to_file,b_machine_hierarchy,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15749).
tcltk_call(write_dot_event_hierarchy_to_file,b_machine_hierarchy,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15754).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15770).
tcltk_call(tcltk_print_states_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15772).
tcltk_call(tcltk_print_states_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15779).
tcltk_call(tcltk_print_neighbourhood_states_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15795).
tcltk_call(b_reset_machine_goal_from_DEFINITIONS,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15801).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15846).
tcltk_call(generate_dot_from_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15853).
tcltk_call(generate_dot_from_assertions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15855).
tcltk_call(generate_dot_from_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15857).
tcltk_call(generate_dot_from_deadlock_po,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15859).
tcltk_call(generate_dot_from_last_span_predicate,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15861).
tcltk_call(generate_dot_from_operation,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15863).
tcltk_call(generate_dot_from_invariant,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15865).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15880).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15881).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15892).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15905).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15912).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15922).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15927).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15932).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15952).
tcltk_call(write_transition_diagram_for_expr_to_dotfile,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15970).
tcltk_call(b_or_z_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15987).
tcltk_call(current_state_corresponds_to_initialised_b_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16005).
tcltk_call(initialised_b_state_exists,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16015).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16029).
tcltk_call(compute_covered_values_for_expression,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16040).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16047).
tcltk_call(tcltk_compute_nr_covered_values_for_all_variables,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16054).
tcltk_call(tcltk_evaluate_expression_over_history,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16070).
tcltk_call(tcltk_print_current_state_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16091).
tcltk_call(tcltk_generate_state_custom_dot_graph,state_custom_dot_graph,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16095).
tcltk_call(tcltk_print_current_state_as_graph_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16099).
tcltk_call(print_cstate_graph,graph_canon,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16100).
tcltk_call(tcltk_print_shortest_trace_to_current_state_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16118).
tcltk_call(tcltk_print_history_to_current_state_for_dot,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16120).
tcltk_call(print_dot_for_dfa_from_nfa,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16152).
tcltk_call(tcltk_write_signature_merge_to_dotfile,state_space_reduction,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16154).
tcltk_call(reduce_graph_state_space,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16171).
tcltk_call(print_subgraph_associated_with_invariant_violations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16173).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16187).
tcltk_call(create_enable_graph,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16194).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16206).
tcltk_call(create_enable_graphs,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16213).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16226).
tcltk_call(print_base_guide,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16233).
tcltk_call(animation_minor_mode,specfile,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16246).
tcltk_call(print_event_guide,flow,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16257).
tcltk_call(debug_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16275).
tcltk_call(run_time_type_check_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16276).
tcltk_call(trace_upon_error,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16277).
tcltk_call(tcltk_print_states_for_fdr,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16312).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16313).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16321).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16328).
tcltk_call(tcltk_print_states_for_fdr,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16334).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16359).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16361).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16419).
tcltk_call(b_write_machine_representation_to_file,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16423).
tcltk_call(tcltk_print_states_for_spin,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16439).
tcltk_call(promela_save_as_neverclaim,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16448).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16474).
tcltk_call(tcltk_get_image_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16475).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16613).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16615).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16622).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16630).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16634).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16639).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16642).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16645).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16647).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16652).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16655).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16657).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16659).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16662).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16665).
tcltk_call(tcltk_eval_string_in_cur_state,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16667).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16698).
tcltk_call(counter_example_can_be_replayed,symbolic_model_checker,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16704).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16721).
tcltk_call(tcltk_unsat_core_properties,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16722).
tcltk_call(query,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16732).
tcltk_call(desired_user_transition,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16758).
tcltk_call(transition_arg_dont_cares,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16783).
tcltk_call(which,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16801).
tcltk_call(get_transition_arguments_from_source,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16807).
tcltk_call(assert_transition_dont_cares,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16832).
tcltk_call(desired_user_transition,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16843).
tcltk_call(use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16851).
tcltk_call(use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16856).
tcltk_call(use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16884).
tcltk_call(use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16890).
tcltk_call(desired_user_transition,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16962).
tcltk_call(retractall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16969).
tcltk_call(user_has_made_op_selection,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16981).
tcltk_call(runtime_application_path,pathes,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17078).
tcltk_call(absolute_file_name,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17080).
tcltk_call(absolute_file_name,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17082).
tcltk_call(print_message,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17084).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17088).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17093).
tcltk_call(tcltk_enabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17098).
tcltk_call(tcltk_cbc_enabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17113).
tcltk_call(tcltk_cbc_simultaneous_enabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17121).
tcltk_call(tcltk_cbc_dependence_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17128).
tcltk_call(get_state_space_stats,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17133).
tcltk_call(tcltk_exists_an_open_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17134).
tcltk_call(tcltk_operations_covered_info,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17146).
tcltk_call(tcltk_compute_mcdc_operation_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17154).
tcltk_call(tcltk_compute_mcdc_invariant_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17162).
tcltk_call(tcltk_cbc_cfg_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17170).
tcltk_call(tcltk_disabling_analysis,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17194).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17455).
tcltk_call(prologTaskStart,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17458).
tcltk_call(walltime,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17478).
tcltk_call(prologTaskStep,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17485).
tcltk_call(prologTaskAbort,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17494).
tcltk_call(prologTaskFinish,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17500).
tcltk_call(walltime,tools,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17501).
tcltk_call('Task',undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17512).
tcltk_call(set_translation_mode,bvisual2,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17609).
tcltk_call(host_platform,tools,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',12).
tcltk_call(use_module,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',23).
tcltk_call(reset_tcltk_tree_inspector,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',31).
tcltk_call(tti_number_of_columns,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',49).
tcltk_call(tti_column_info,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',64).
tcltk_call(tti_column_info,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',83).
tcltk_call(tti_get_node_info,tcltk_tree_inspector,'/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl',132).
tcltk_call(print_trace_as_fdr_check,b_trace_checking,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',534).
tcltk_call(analyze_hash_collisions,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',832).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',899).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',901).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',993).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',994).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1003).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1005).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1005).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1007).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1007).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1011).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1013).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1016).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1018).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1020).
tcltk_call(set_preference_group,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1022).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1450).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1452).
tcltk_call(get_recent_documents,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1531).
tcltk_call(clear_recent_documents,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1546).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1912).
tcltk_call(ops_with_virtual_timeout,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1914).
tcltk_call(ops_with_real_timeout,eclipse_interface,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1915).
tcltk_call(tcltk_mark_current_node_to_be_recomputed_wo_timeout,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1944).
tcltk_call(tcltk_mark_current_node_to_be_recomputed_with_random_enum,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1952).
tcltk_call(tcltk_finish_current_node_to_be_recomputed_with_random_enum,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',1956).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2437).
tcltk_call(get_preference,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',2699).
tcltk_call(startzconversiontests,proz,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5347).
tcltk_call(set_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5445).
tcltk_call(tcltk_compute_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5448).
tcltk_call(tcltk_compute_coverage,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5492).
tcltk_call(tcltk_clear_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5767).
tcltk_call(get_recent_documents,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',5858).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6302).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6351).
tcltk_call(tcltk_clear_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6382).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',6427).
tcltk_call(tcltk_reset,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7349).
tcltk_call(tcltk_fast_forward,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7354).
tcltk_call(tcltk_execute_trace_to_current_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7503).
tcltk_call(tcltk_find_shortest_trace_to_current_node,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7539).
tcltk_call(backup_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7599).
tcltk_call(get_preferences_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7638).
tcltk_call(revert_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7654).
tcltk_call(reset_to_defaults,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7662).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7674).
tcltk_call(get_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7675).
tcltk_call(get_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7702).
tcltk_call(get_ith_preference_type,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7734).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7738).
tcltk_call(set_ith_preference_value,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',7740).
tcltk_call(tcltk_top_level_operations,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8109).
tcltk_call(findall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8117).
tcltk_call('Query',undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8269).
tcltk_call(tcltk_analyse,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8362).
tcltk_call(tcltk_analyse_goal,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8393).
tcltk_call(tcltk_show_typing_of_variables_and_constants,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',8404).
tcltk_call(tcltk_reset,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9558).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',9872).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10047).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10113).
tcltk_call(backup_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10368).
tcltk_call(reset_for_benchmarking,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10369).
tcltk_call(deactivate_recent_documents,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10370).
tcltk_call(revert_preferences,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10415).
tcltk_call(activate_recent_documents,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10416).
tcltk_call(count_errors_occurred,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10509).
tcltk_call(get_all_errors,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10512).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10637).
tcltk_call(tcltk_cbc_refinement_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10859).
tcltk_call(tcltk_constraint_based_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',10871).
tcltk_call(tcltk_get_options_dest_info,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11151).
tcltk_call(tcltk_get_status,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11189).
tcltk_call(findall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11817).
tcltk_call(findall,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',11921).
tcltk_call(animation_mode,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15133).
tcltk_call(host_platform,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15135).
tcltk_call(get_preferences_list,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15140).
tcltk_call(prob_licence,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15252).
tcltk_call(prob_licence,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15273).
tcltk_call(mc_summary,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15341).
tcltk_call(symmetry_summary,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',15357).
tcltk_call(tcl_get_events_preselected,sap,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16130).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16280).
tcltk_call(tcltk_turn_debugging_on,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16288).
tcltk_call(tcltk_turn_debugging_off,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16290).
tcltk_call(turn_on_run_time_type_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16293).
tcltk_call(turn_off_run_time_type_checks,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16295).
tcltk_call(turn_trace_upon_error_on,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16298).
tcltk_call(debug,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16299).
tcltk_call(turn_trace_upon_error_off,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16302).
tcltk_call(nodebug,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16303).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16335).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16369).
tcltk_call(get_preference,preferences,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16387).
tcltk_call(symbolic_model_check,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16699).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16865).
tcltk_call(set_use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16871).
tcltk_call(user_made_op_selection,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16952).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16971).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16982).
tcltk_call(set_use_all_operations,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',16983).
tcltk_call(user_made_arg_selection,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17004).
tcltk_call(set_use_no_arguments,reduce_graph_state_space,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17017).
tcltk_call(tcltk_set_initial_machine,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17582).
tcltk_call(tcltk_initialise,undefined_module,'/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl',17593).
