/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/ast_inspector.tcl:90: ast_inspector:tcltk_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:22: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:86: tcltk_bv_get_tops
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:125: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:132: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:139: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:147: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:149: tcltk_bv_get_unlimited_value
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:213: tcltk_bv_get_value
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:235: tcltk_bv_get_structure
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:473: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:476: "bvisual2:bv_print_to_file
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:485: "current_expression
/Users/leuschel/git_root/prob_prolog/tcl/evaluation_view.tcl:487: "bvisual2:bv_write_all_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:41: version:version
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:44: prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:47: version:revision
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:49: version:lastchangeddate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:214: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:230: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:254: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:256: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:270: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:270: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:285: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:322: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:323: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:496: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:762: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:768: self_checks_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:790: debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:812: b_normal_form:print_normal_forms
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:818: (nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:821: state_space_initialise_with_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:890: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:902: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:905: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:908: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:911: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:916: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:933: preferences:print_non_default_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:938: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:941: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:944: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:947: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:977: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:982: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1058: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1067: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1080: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1093: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1122: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1143: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1150: "cspm_file_add_remove_unicode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1185: "tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1187: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1229: "tcltk_show_expression_as_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1247: "tcltk_eval_as_table
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1248: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1308: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1310: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1320: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1327: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1527: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1581: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1582: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1589: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1752: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1758: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1762: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1796: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1813: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1834: tcltk_has_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1847: tcltk_show_eventtrace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1859: tcltk_get_detailed_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1864: can_generate_dot_from_last_state_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1891: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1897: "eclipse_interface:ops_user_interrupt_occured
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1910: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1919: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1924: plugins:plugin_has_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1925: plugins:plugins_with_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1943: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1946: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1949: get_specification_description
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1962: plugins:plugin_is_available_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1963: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1981: plugins:start_plugin_for_current_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1994: plugins:plugin_has_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1997: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2009: plugins:plugin_get_output
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2026: plugins:stop_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2037: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2040: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2049: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2051: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2059: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2093: "animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2120: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2139: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2142: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2312: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2328: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2348: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2350: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2352: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2353: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2530: "animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2671: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2950: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2952: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3143: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:3358: system:environ
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5441: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5449: tcltk_goto_an_invariant_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5470: spec_file_has_been_successfully_loaded
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5481: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5492: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5505: perform_verbose_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5518: get_module_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5521: perform_self_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5576: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5579: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5632: plugins:plugin_file_extensions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5659: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5665: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5679: "unset_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5696: plugins:is_plugin_file_extension
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5704: plugins:available_plugins_for_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5732: tcltk_load_packaged_eventb_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5736: bmachine:b_show_machine_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5793: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5799: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5802: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5806: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5810: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5813: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5816: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5819: tcltk_get_command_line_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5827: tcltk_get_command_line_file_to_open
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5834: tcltk_get_command_line_tcltk_commands
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5852: tcltk_open_xtl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5958: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5963: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5965: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5986: tcltk_open_z_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6008: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6038: eclipse_interface:load_prob_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6039: tcltk_open_b_file_for_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6043: set_animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6100: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6124: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6125: "tools:platform_is_64_bit
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6164: plugins:load_plugin_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6189: tcltk_open_promela_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6217: tcltk_open_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6232: "set_tcltk_cspm_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6244: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6310: tcltk_add_csp_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6369: tcltk_open_b_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6496: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6498: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6532: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6558: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6578: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6579: plugins:tcl_plugin_syntax_colouring
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6600: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6628: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6632: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6637: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6640: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6646: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6651: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6655: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6663: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6676: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6680: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6686: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6692: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6699: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6703: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6711: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6717: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6725: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6750: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6753: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6757: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6762: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6767: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6771: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6775: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6779: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6788: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6791: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6795: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6799: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6803: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6815: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6818: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6823: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6828: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6832: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6837: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6842: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6847: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6857: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6860: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6865: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6869: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6874: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6878: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6882: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6891: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6894: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6899: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6905: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6911: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6916: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6927: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6949: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6978: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7015: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7016: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7019: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7022: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7025: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7028: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7031: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7034: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7037: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7072: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7107: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7119: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7129: "b_show_history:write_values_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7156: preferences:add_recent_document
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7254: plugins:active_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7265: tcltk_prepare_for_reload
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7280: plugins:is_registered_plugin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7328: tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7334: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7409: tcltk_random_perform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7412: tcltk_current_state_invariant_violated
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7421: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7448: tcltk_execute_until
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7476: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7533: cli_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7534: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7536: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7539: preferences:save_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7545: tcltk_load_commandline_prefs_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7548: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7549: file_systems:file_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7550: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7552: preferences:load_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7671: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7684: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7686: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7707: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7709: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7790: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7791: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7800: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7801: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7802: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7803: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7804: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7805: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7815: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7815: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7816: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7816: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7817: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7818: "set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7825: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7833: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7937: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7940: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7969: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7970: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7974: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8033: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8034: tcltk_unique_top_level_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8039: current_state_corresponds_to_setup_constants_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8113: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8140: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8140: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8147: b_get_machine_operation_parameter_names
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8211: tcltk_add_user_executed_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8223: query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8224: interruptable_call
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8234: query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8235: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8236: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8238: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8291: interruptable_call
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8324: tcltk_analyse_option
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8350: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8376: tcltk_show_current_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8522: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8526: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8535: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8544: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8545: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8553: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8585: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8587: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8592: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8606: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8610: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8636: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8639: parsercall:ensure_console_parser_launched
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8737: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8809: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8815: last_expression_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8823: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8845: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8854: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8863: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8883: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8969: tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8975: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8978: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8996: "interruptable_tcltk_eval
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9002: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9007: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9045: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9181: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9182: popup
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9190: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9191: bmachine:tcltk_get_specialized_invariants_for_ops
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9199: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9203: bmachine:tcltk_get_specialized_invariant_for_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9213: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9217: before_after_predicates:tcltk_before_after_predicate_for_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9227: value_persistance:tcltk_load_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9237: runtime_profiler:tcltk_get_profile_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9254: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9259: model_checking_is_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9319: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9342: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9343: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9351: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9353: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9354: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9360: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9364: bmachine:b_write_eventb_machine_to_classicalb_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9557: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9583: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9592: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9647: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9648: tcltk_get_constants_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9716: tcltk_dbf_modes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9725: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9737: bmachine:b_get_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9746: tcltk_machine_has_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9753: operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9759: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9796: tcltk_state_space_only_has_root_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9804: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9829: tcltk_set_dbf_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9844: "prolog_flag
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9846: "nl
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9847: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9868: "statistics
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9870: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9874: tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9879: state_space:operation_name_not_yet_covered
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9882: model_checker:proof_info_model_checking_incomplete
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9885: time_out_for_invariant
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9889: tcltk_hash_model_checking_imprecise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9896: state_error_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9947: tcltk_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10045: cbc_get_uncovered_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10049: sap:tcl_get_stored_test_cases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10071: tcl_execute_stored_test_case
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10091: sap:tcl_generate_testcases
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10212: sap:tcl_create_local_testsuite
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10294: set_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10295: specfile:get_internal_representation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10302: unset_unicode_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10306: predicate_debugger:tcltk_get_unsat_core_with_types
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10313: bmachine:b_show_eventb_as_classicalb
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10391: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10402: b_set_machine_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10409: get_error_span_linecol
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10412: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10423: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10431: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10436: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10457: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10462: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10482: tcltk_goto_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10490: tcltk_goto_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10499: tcltk_goto_a_non_resetable_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10508: tcltk_goto_a_non_deterministic_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10515: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10518: tcltk_goto_node_with_id
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10527: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10536: tcltk_goto_a_branching_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10549: tcltk_search_among_existing_nodes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10555: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10601: tcltk_goto_event_list_property_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10605: sap:get_selected_events
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10606: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10621: tcltk_goto_state_enabling_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10624: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10649: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10651: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10678: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10718: ctl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10724: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10730: state_space:max_nr_of_new_nodes_limit_not_reached
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10762: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10763: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10773: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10778: tcltk_constraint_find_valid_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10784: tcltk_constraint_find_valid_state_with_goal_pred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10799: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10815: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10823: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10828: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10833: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10840: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10841: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10855: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10859: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10860: tcltk_constraint_find_deadlock_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10873: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10878: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10879: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10892: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10897: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10898: tcltk_constraint_find_static_assertion_violation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10918: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10922: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10922: unfixed_deferred_set
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11017: get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11051: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11058: and
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11095: {tcltk_get_options
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11123: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11123: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11124: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11125: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11154: tcltk_current_node_has_no_real_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11156: bmachine:bmachine_is_precompiled
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11156: b_machine_has_constants_or_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11156: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11158: tcltk_current_node_has_partial_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11159: preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11180: b_interpreter:tcltk_unsatisfiable_components_exist
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11196: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11196: current_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11201: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11207: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11218: b_interpreter:tcltk_quick_describe_unsat_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11229: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11234: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11236: {get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11237: {get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11238: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11249: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11261: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11298: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11322: {tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11338: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11342: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11374: tcltk_can_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11381: tcltk_can_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11394: and
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11406: {tcltk_get_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11422: and
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11428: {tcltk_get_state_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11442: and
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11448: {tcltk_get_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11473: tcltk_get_line_col
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11484: tcltk_is_sync_event
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11509: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11523: tcltk_no_constants_or_no_inititalisation_found
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11528: tcltk_perform_nr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11540: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11550: tcltk_backtrack
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11555: tcltk_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11581: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11736: get_cbc_data_base_id_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11736: get_cbc_data_base_text_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11944: tcltk_constraint_based_check_op
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11948: tcltk_cbc_find_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11952: tcltk_constraint_find_deadlock_state_with_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11955: assert_real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11961: temporary_set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11963: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11979: reset_temporary_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11985: tcltk_perform_cbc_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12033: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12055: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12093: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12134: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12186: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12248: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12427: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12500: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12511: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12621: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12637: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12639: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12670: "get_csp_processes
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12904: "get_ltl_formulas_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12921: parse_and_load_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12962: "get_writable_compiled_filename
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12964: "parse_and_load_cspm_file_into_specific_pl_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:12988: "generate_temporary_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13018: "eval_elapsed_time
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13035: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13035: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13038: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13041: reset_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13328: "user:
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13330: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13394: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13793: side
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13795: "tcltk_check_csp_assertion
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13808: real_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13844: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:13899: "get_csp_assertions_as_string
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14131: call
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14246: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14248: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14358: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14362: set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14366: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14406: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14409: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14433: "tcltk_play_ltl_ctl_counterexample_trace
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14444: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14447: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14459: "
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14460: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14468: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14539: "ltl:
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14548: "ctl:
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14620: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14657: ltl_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14683: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14724: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14730: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14733: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14753: [subst
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14789: assert_cli_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14879: preferences:add_element_to_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14896: preferences:get_history_elements_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14903: bmachine:b_get_definition_string_from_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14905: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14905: haskell_csp:get_formulas_from_cspm_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:14959: bmachine:b_get_definition_string_from_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15008: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15013: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15105: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15120: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15126: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15144: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15148: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15340: "tcltk_save_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15353: "tcltk_load_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15373: "tcltk_save_specification_state_for_refinement
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15375: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15377: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15386: {bmachine:b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15408: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15410: "tcltk_find_max_reached_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15484: {b_get_machine_refinement_hierarchy
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15567: tcltk_load_refine_spec_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15568: tcltk_refinement_search
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15575: "tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15602: "b_show_history:write_history_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15619: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15623: "tcltk_save_history_as_trace_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15670: "tcltk_check_state_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15673: "tcltk_check_sequence_from_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15677: test_error_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15706: "b_machine_hierarchy:write_dot_hierarchy_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15711: "b_machine_hierarchy:write_dot_event_hierarchy_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15727: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15729: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15736: "tcltk_print_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15752: "tcltk_print_neighbourhood_states_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15758: b_reset_machine_goal_from_DEFINITIONS
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15803: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15810: "generate_dot_from_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15812: "generate_dot_from_assertions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15814: "generate_dot_from_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15816: "generate_dot_from_deadlock_po
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15818: "generate_dot_from_last_span_predicate
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15820: generate_dot_from_operation
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15822: "generate_dot_from_invariant
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15837: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15838: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15849: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15862: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15869: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15879: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15884: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15889: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15909: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15927: "write_transition_diagram_for_expr_to_dotfile
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15944: b_or_z_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15962: current_state_corresponds_to_initialised_b_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15972: initialised_b_state_exists
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15986: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15997: "compute_covered_values_for_expression
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16004: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16011: "tcltk_compute_nr_covered_values_for_all_variables
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16027: "tcltk_evaluate_expression_over_history
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16048: "tcltk_print_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16052: "state_custom_dot_graph:tcltk_generate_state_custom_dot_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16056: "tcltk_print_current_state_as_graph_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16057: "graph_canon:print_cstate_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16075: "tcltk_print_shortest_trace_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16077: "tcltk_print_history_to_current_state_for_dot
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16109: "reduce_graph_state_space:print_dot_for_dfa_from_nfa
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16111: "state_space_reduction:tcltk_write_signature_merge_to_dotfile
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16128: "reduce_graph_state_space:
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16130: "reduce_graph_state_space:print_subgraph_associated_with_invariant_violations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16144: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16151: "flow:create_enable_graph
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16163: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16170: "flow:create_enable_graphs
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16183: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16190: "flow:print_base_guide
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16203: "specfile:animation_minor_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16214: "flow:print_event_guide
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16232: "debug_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16233: "run_time_type_check_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16234: "trace_upon_error
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16269: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16270: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16278: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16285: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16291: "tcltk_print_states_for_fdr
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16316: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16318: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16376: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16380: b_write_machine_representation_to_file
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16396: "tcltk_print_states_for_spin
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16405: "promela_save_as_neverclaim
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16431: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16432: tcltk_get_image_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16570: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16572: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16579: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16587: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16591: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16596: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16599: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16602: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16604: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16609: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16612: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16614: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16616: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16619: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16622: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16624: "tcltk_eval_string_in_cur_state
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16655: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16661: symbolic_model_checker:counter_example_can_be_replayed
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16678: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16679: "tcltk_unsat_core_properties
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16689: query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16691: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16715: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16740: "reduce_graph_state_space:transition_arg_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16758: which
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16764: "reduce_graph_state_space:get_transition_arguments_from_source
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16789: "reduce_graph_state_space:assert_transition_dont_cares
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16800: "reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16808: reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16813: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16841: "reduce_graph_state_space:use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16847: "reduce_graph_state_space:use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16919: "(reduce_graph_state_space:desired_user_transition
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16926: "retractall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16938: reduce_graph_state_space:user_has_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17035: pathes:runtime_application_path
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17037: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17039: absolute_file_name
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17041: "tools:print_message
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17045: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17050: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17055: tcltk_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17070: tcltk_cbc_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17078: tcltk_cbc_simultaneous_enabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17085: tcltk_cbc_dependence_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17090: get_state_space_stats
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17091: tcltk_exists_an_open_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17103: tcltk_operations_covered_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17111: tcltk_compute_mcdc_operation_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17119: tcltk_compute_mcdc_invariant_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17127: tcltk_cbc_cfg_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17151: tcltk_disabling_analysis
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17172: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17412: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17415: prologTaskStart
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17435: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17442: prologTaskStep
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17451: prologTaskAbort
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17457: prologTaskFinish
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17458: "tools:walltime
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17469: Task
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17566: bvisual2:set_translation_mode
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:12: tools:host_platform
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:23: "use_module
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:31: tcltk_tree_inspector:reset_tcltk_tree_inspector
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:49: tcltk_tree_inspector:tti_number_of_columns
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:64: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:83: tcltk_tree_inspector:tti_column_info
/Users/leuschel/git_root/prob_prolog/tcl/tree_inspector.tcl:132: tcltk_tree_inspector:tti_get_node_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:532: b_trace_checking:print_trace_as_fdr_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:829: analyze_hash_collisions
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:896: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:898: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:990: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:991: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1000: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1002: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1002: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1004: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1004: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1008: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1010: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1013: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1015: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1017: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1019: preferences:set_preference_group
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1413: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1415: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1494: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1509: preferences:clear_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1874: "preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1876: "eclipse_interface:ops_with_virtual_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1877: "eclipse_interface:ops_with_real_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1906: tcltk_mark_current_node_to_be_recomputed_wo_timeout
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1914: tcltk_mark_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:1918: tcltk_finish_current_node_to_be_recomputed_with_random_enum
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2399: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:2661: "get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5309: proz:startzconversiontests
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5407: preferences:set_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5410: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5454: tcltk_compute_coverage
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5729: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:5820: get_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6267: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6316: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6347: tcltk_clear_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:6392: tcltk_initialise
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7313: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7318: tcltk_fast_forward
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7467: tcltk_execute_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7503: tcltk_find_shortest_trace_to_current_node
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7563: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7602: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7618: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7626: reset_to_defaults
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7638: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7639: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7666: get_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7698: get_ith_preference_type
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7702: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:7704: set_ith_preference_value
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8073: tcltk_top_level_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8081: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8233: {Query
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8326: tcltk_analyse
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8357: tcltk_analyse_goal
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:8368: tcltk_show_typing_of_variables_and_constants
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9522: tcltk_reset
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:9836: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10011: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10077: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10326: preferences:backup_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10327: preferences:reset_for_benchmarking
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10328: preferences:deactivate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10373: preferences:revert_preferences
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10374: preferences:activate_recent_documents
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10467: count_errors_occurred
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10470: get_all_errors
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10595: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10817: tcltk_cbc_refinement_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:10829: tcltk_constraint_based_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11108: tcltk_get_options_dest_info
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11146: tcltk_get_status
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11774: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:11878: findall
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15090: animation_mode
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15092: host_platform
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15097: get_preferences_list
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15209: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15230: prob_licence
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15261: 
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15298: mc_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:15314: symmetry_summary
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16087: sap:tcl_get_events_preselected
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16237: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16245: "tcltk_turn_debugging_on
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16247: "tcltk_turn_debugging_off
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16250: "turn_on_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16252: "turn_off_run_time_type_checks
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16255: "turn_trace_upon_error_on
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16256: "debug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16259: "turn_trace_upon_error_off
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16260: "nodebug
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16292: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16326: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16344: preferences:get_preference
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16656: "symbolic_model_check
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16822: "reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16828: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16909: reduce_graph_state_space:user_made_op_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16928: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16939: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16940: reduce_graph_state_space:set_use_all_operations
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16961: reduce_graph_state_space:user_made_arg_selection
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:16974: "reduce_graph_state_space:set_use_no_arguments
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17539: tcltk_set_initial_machine
/Users/leuschel/git_root/prob_prolog/tcl/main_prob_tcltk_gui.tcl:17550: tcltk_initialise
